services:
  devbox:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - .:/workspace:cached
      - /run/user/1000/docker.sock:/var/run/docker.sock
    command: sleep infinity
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/elib_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    privileged: true