apiVersion: v1
kind: Secret
metadata:
  name: elib-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | default "postgres" | quote }}
  jwt-secret: {{ .Values.jwtSecret | default "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970" | quote }}
  rabbitmq-user: {{ .Values.rabbitmq.user | default "guest" | quote }}
  rabbitmq-pass: {{ .Values.rabbitmq.pass | default "guest" | quote }}
  mail-username: {{ .Values.mail.username | default "" | quote }}
  mail-password: {{ .Values.mail.password | default "" | quote }}
