spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: never

server:
  port: 8084
  servlet:
    context-path: /api

logging:
  level:
    com.elib.catalog: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha